name       : geary
version    : 40.0
release    : 31
source     :
    - https://download.gnome.org/sources/geary/40/geary-40.0.tar.xz : 3356203725a924d6cb358e0c29ad090f4177d8d7b7f8210412cf0250ca6856b0
license    :
    - BSD-2-Clause # Snowball
    - CC-BY-SA-3.0 # Icons
    - LGPL-2.1-or-later # Source
summary    : Geary is a mail client for GNOME
description: |
    Geary is a mail client for GNOME
component  : network.mail
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(enchant-2)
    - pkgconfig(folks)
    - pkgconfig(gcr-3)
    - pkgconfig(gee-0.8)
    - pkgconfig(gmime-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gsound)
    - pkgconfig(gspell-1)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libunwind)
    - pkgconfig(libytnef)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - libstemmer-devel
    - valadoc
rundeps    :
    - gnome-keyring
setup      : |
    %apply_patches
    %meson_configure -Dprofile=release
build      : |
    %ninja_build
install    : |
    %ninja_install
