name       : geary
version    : 0.13.0
release    : 18
source     :
    - https://download.gnome.org/sources/geary/0.13/geary-0.13.0.tar.xz : 4fd9bca851678b623c124e6e7ccb3629c304b7c025a370d0a6524bdb633dbe7f
license    :
    - BSD-2-Clause # Snowball
    - CC-BY-SA-3.0 # Icons
    - LGPL-2.1-or-later # Source
summary    : Geary is a mail client for GNOME 3
description: |
    Geary is a mail client for GNOME 3.
component  : network.mail
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gcr-3)
    - pkgconfig(gee-0.8)
    - pkgconfig(gmime-2.6)
    - pkgconfig(goa-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libunwind)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - valadoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
