name        : geary
version     : 0.10.0
release     : 3
source      :
    - https://download.gnome.org/sources/geary/0.10/geary-0.10.0.tar.xz : 46197a5a1b8b040adcee99082dbfd9fff9ca804e3bf0055a2e90b13214bdbca5
homepage    : https://wiki.gnome.org/Apps/Geary
license     :
    - LGPL-2.1
summary     : Geary is a mail client for GNOME 3. 
builddeps   :
    - pkgconfig(xml2po)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsecret-1)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra)
    - pkgconfig(sqlite3)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gcr-3)
    - gettext-devel
    - desktop-file-utils
    - vala
description : |
    Geary is a mail client for GNOME 3.
setup      : |
    ./configure --prefix=/usr --libdir=%libdir%
build      : |
    %make
install    : |
    %make_install
