name       : geary
version    : 3.32.1
release    : 23
source     :
    - https://download.gnome.org/sources/geary/3.32/geary-3.32.1.tar.xz : eedc6f2d40e8131fa08990ffda1b77a53a153b77070c84f26dcf1dbb4a8cc51f
license    :
    - BSD-2-Clause # Snowball
    - CC-BY-SA-3.0 # Icons
    - LGPL-2.1-or-later # Source
summary    : Geary is a mail client for GNOME 3
description: |
    Geary is a mail client for GNOME 3.
component  : network.mail
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(folks)
    - pkgconfig(gcr-3)
    - pkgconfig(gee-0.8)
    - pkgconfig(gmime-2.6)
    - pkgconfig(goa-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libunwind)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - valadoc
rundeps    :
    - gnome-keyring
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
