name       : geary
version    : 0.12.3
release    : 16
source     :
    - https://download.gnome.org/sources/geary/0.12/geary-0.12.3.tar.xz : 87bbf8ed650e67932fe49e70071b8ba4d4df7296dbdbdb0150f29703f497ffa3
license    :
    - BSD-2-Clause # Snowball
    - CC-BY-SA-3.0 # Icons
    - LGPL-2.1-or-later # Source
summary    : Geary is a mail client for GNOME 3.
description: |
    Geary is a mail client for GNOME 3.
component  : network.mail
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gcr-3)
    - pkgconfig(gee-0.8)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(xml2po)
    - desktop-file-utils
    - gnome-doc-utils
    - valadoc
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
