name       : geary
version    : 0.11.1
release    : 6
source     :
    - https://download.gnome.org/sources/geary/0.11/geary-0.11.1.tar.xz : 6efc5e1a944ca1c1a991d50d558fbe46ed58763b3f8b7bcd451b15078a9b2eb2
license    : LGPL-2.1
summary    : Geary is a mail client for GNOME 3.
description: |
    Geary is a mail client for GNOME 3.
component  : network.mail
builddeps  :
    - pkgconfig(xml2po)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsecret-1)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra)
    - pkgconfig(sqlite3)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gcr-3)
    - gettext-devel
    - desktop-file-utils
    - vala
setup      : |
    ./configure --prefix=/usr --libdir=%libdir%
build      : |
    %make
install    : |
    %make_install
