name       : geary
version    : 0.12.0
release    : 11
source     :
    - https://download.gnome.org/sources/geary/0.12/geary-0.12.0.tar.xz : cef1093033ddfb52942b45c901562539cee7a192e981c7f19e2075ecb0c22446
license    : LGPL-2.1
summary    : Geary is a mail client for GNOME 3.
description: |
    Geary is a mail client for GNOME 3.
component  : network.mail
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gcr-3)
    - pkgconfig(gee-0.8)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(xml2po)
    - desktop-file-utils
    - gnome-doc-utils
    - vala
    - valadoc
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
