name        : geary
version     : 0.11.0
release     : 5
source     :
    - https://download.gnome.org/sources/geary/0.11/geary-0.11.0.tar.xz : c947bb1e70bd3d3f4799e59ddd05b27b08a8132674f64c68c919974595bdcd9f
license     : LGPL-2.1
summary     : Geary is a mail client for GNOME 3. 
description : |
    Geary is a mail client for GNOME 3.
component   : network.mail
builddeps   :
    - pkgconfig(xml2po)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsecret-1)
    - pkgconfig(libnotify)
    - pkgconfig(libcanberra)
    - pkgconfig(sqlite3)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gcr-3)
    - gettext-devel
    - desktop-file-utils
    - vala
setup      : |
    ./configure --prefix=/usr --libdir=%libdir%
build      : |
    %make
install    : |
    %make_install
